#!/bin/bash

listrpi=(rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18
	)

	for i in " ${listrpi[@]}"; do
		echo "$i"
		ping "$i" -c 1 -W 1 2>&1 >/dev/null 
			if [ "$i" -eq 0 ];then
				echo  "alive"
			else
				echo  "dead"
			fi
done
